---
title: "clusterProfiler: The 'Paintbrush' for Portraying Multi-Omics Data"
subtitle: "online example data"
author: "Maintained by YuLab-SMU"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
  pdf_document:
    toc: true
---
# Directory introduction

This directory contains the files used in Phyllostachys_heterocycla example.

annot_data directory contains three files: Phe_GO_annotation.txt, Phe_TF_list.txt, 
regulation_from_motif_CE_Phe.txt.

Phe_GO_annotation.txt: The Phyllostachys Edulis gene GO annotation data was downloaded from http://planttfdb.gao-lab.org/.

Phe_TF_lwast.txt: The Phyllostachys Edulis transcription factor family annotation data was downloaded from http://planttfdb.gao-lab.org/.

regulation_from_motif_CE_Phe.txt: The Predicted Phyllostachys Edulis transcription factor target gene was downloaded from http://planttfdb.gao-lab.org/.

counts.txt: The counts.txt was processed Phyllostachys Edulis gene count matrix derived from https://db.cngb.org/search/project/CNP0002243/.

group_info.txt: The Phyllostachys Edulis sample group infomation was derived from https://onlinelibrary.wiley.com/doi/10.1111/jipb.13357.

# Data link
```{r echo=FALSE}
library(fs)
x <- dir_info('examples/Phyllostachys_heterocycla',
  recurse = TRUE, regexp = "[.]html$", invert = TRUE)[, 1:3] |>
    as.data.frame()

x_link <- gsub(x$path, pattern = "examples/Phyllostachys_heterocycla/",
  replacement = ""
)
x$path <- sprintf("[%s](%s)", x_link, x_link)

knitr::kable(x, row.names = FALSE)
```